CREATE TABLE IF NOT EXISTS users {
    id serial PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

CREATE TABLE IF NOT EXISTS rooms {
    id serial PRIMARY KEY,
    room_name VARCHAR(100) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

CREATE TABLE IF NOT EXISTS messages {
    id serial PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    room_id INT REFERENCES rooms(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

CREATE INDEX IF NOT EXISTS idx_messages_room_created_at 
ON messages(room_id, created_at DESC);
ALTER TABLE users ADD COLUMN password varchar(255) NOT NULL DEFAULT '';
